CREATE DATABASE TVSchedulingDB;
GO

USE TVSchedulingDB;

CREATE TABLE Schedule (
    ScheduleID INT PRIMARY KEY,
    ChannelID INT,
    ProgramID NVARCHAR(100),
    StartTime DATETIME,
    EndTime DATETIME,
    ImagePath NVARCHAR(255)
);

CREATE TABLE Users (
    UserID INT IDENTITY PRIMARY KEY,
    Username NVARCHAR(50) UNIQUE NOT NULL,
    Password NVARCHAR(100) NOT NULL,
    Role NVARCHAR(20) NOT NULL
);

SELECT * FROM Schedule
